### PR TITLE
fix: graceful shutdown of orphaned test apps on windows

### LINKED ISSUE #407: Fix multi app DTD test on windows
See https://github.com/dart-lang/ai/pull/406

The test works fine, but is failing to clean up for some reason. It gets an error when trying to delete the temp directories, due to some process still holding on there.

### PR DESCRIPTION
**Pull request by Sourav-Sonkar**
Fixes #407

This PR resolves the multi-app DTD test teardown failure on Windows.

**What this PR changes:**
- Modified the test dummy applications in `dtd_multiple_connection_test.dart` and `infinite_wait.dart` to gracefully shut down by listening to `stdin` and calling `exit(0)` when the pipe is closed.

**Why:**
On Windows, when `AppDebugSession` terminates the parent `dart run` test process via `process.kill()`, the child `dart` process running the infinite `while(true)` loop tends to be left orphaned. This orphaned process maintained a lock on the `d.sandbox` directory, preventing the test framework from deleting the temp directory during teardown and throwing a "file in use" or "access denied" error. By having the test fixture scripts monitor `stdin` and exit on its closure, the child process dies gracefully as soon as the test stops the debug session or the test forcefully crashes.

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.

**Note**: The Dart team is trialing Gemini Code Assist. Don't take its comments as final Dart team feedback. Use the suggestions if they're helpful; otherwise, wait for a human reviewer.

</details>

### CODE REVIEW

File: pkgs/dart_mcp_server/test/tools/dtd_multiple_connection_test.dart
Comment (jakemac53) [inline pkgs/dart_mcp_server/test/tools/dtd_multiple_connection_test.dart]: This is the line that needs to be removed

File: .github/workflows/test-windows.yml [hunk 1]
```diff
@@ -0,0 +1,29 @@
+name: Test on Windows
```
Comment (jakemac53) [inline .github/workflows/test-windows.yml]: Instead of adding a new file here, just remove the skip below (I left a comment on it). This job wouldn't actually run the test (it would be skipped), and the existing job already does run for windows.

Comment (Sourav-Sonkar) [reply .github/workflows/test-windows.yml]: Removed

File: pkgs/dart_mcp_server/test/tools/dtd_multiple_connection_test.dart
Comment (Sourav-Sonkar) [reply pkgs/dart_mcp_server/test/tools/dtd_multiple_connection_test.dart]: Removed

File: pkgs/dart_mcp_server/test/tools/dtd_multiple_connection_test.dart [hunk 2]
```diff
@@ -275,9 +277,7 @@ void main() async {
           contains('error from app 2'),
         );
       },
-      skip: Platform.isWindows
-          ? 'https://github.com/dart-lang/ai/issues/407'
-          : false,
+      skip: false,
```
Comment (jakemac53) [inline pkgs/dart_mcp_server/test/tools/dtd_multiple_connection_test.dart]:
```suggestion
```

**Comment by Sourav-Sonkar** [comment]
@jakemac53  i will check the issue and fix them

**Comment by Sourav-Sonkar** [comment]
@jakemac53 can you please run the workflows

File: pkgs/dart_mcp_server/test/test_harness.dart [hunk 3]
```diff
@@ -322,10 +322,29 @@ final class AppDebugSession {
   static Future<void> kill(TestProcess process, bool isFlutter) async {
     if (isFlutter) {
       process.stdin.writeln('q');
-      await process.shouldExit(0);
```
Comment (jakemac53) [inline pkgs/dart_mcp_server/test/test_harness.dart:325]: Are these try/catch still necessary? It seems like these will just paper over real issues

Comment (Sourav-Sonkar) [reply pkgs/dart_mcp_server/test/test_harness.dart:325]: Changed to on StateError catch (_) with a lint ignore. The catch is legit — kill() gets called twice during teardown (test + harness), so stdin can already be closed on the second pass. Added a comment explaining this. Both Ubuntu and Windows CI passing

Comment (Sourav-Sonkar) [reply pkgs/dart_mcp_server/test/test_harness.dart:325]: @jakemac53  can please check

File: pkgs/dart_mcp_server/test/test_harness.dart [hunk 4]
```diff
@@ -28,7 +28,7 @@ import 'package:unified_analytics/unified_analytics.dart';
 
 Future<T> callWithRetry<T>(
   FutureOr<T> Function() fn, {
-  int maxTries = 5,
+  int maxTries = 10,
```
Comment (jakemac53) [inline pkgs/dart_mcp_server/test/test_harness.dart]: Do we need to bump this to 10 or is this just left over from debugging?

File: pkgs/dart_mcp_server/test/test_harness.dart [hunk 5]
```diff
@@ -275,8 +275,8 @@ final class AppDebugSession {
     final process = await TestProcess.start(
       isFlutter ? sdk.flutterExecutablePath : sdk.dartExecutablePath,
       [
-        'run',
-        '--no${isFlutter ? '' : '-serve'}-devtools',
+        if (isFlutter) 'run',
+        if (isFlutter) '--no-devtools',
```
Comment (jakemac53) [inline pkgs/dart_mcp_server/test/test_harness.dart]: I think these changes should be reverted

File: pkgs/dart_mcp_server/test/test_harness.dart [hunk 6]
```diff
@@ -319,13 +319,48 @@ final class AppDebugSession {
...
-      process.stdin.writeln('q');
-      await process.shouldExit(0);
+      try {
+        process.stdin.writeln('q');
+        // ignore: avoid_catching_errors
+      } on StateError catch (_) {
+        // stdin already closed from a prior kill() call.
+      }
+      try {
+        await process.shouldExit(0).timeout(const Duration(seconds: 10));
```
Comment (jakemac53) [inline pkgs/dart_mcp_server/test/test_harness.dart:338]: These try/catch blocks here will no longer assert a non-zero exit code like they previously did (since we are just catching the test failures)

File: pkgs/dart_mcp_server/test/test_harness.dart [hunk 7]
```diff
@@ -447,9 +482,16 @@ class FakeEditorExtension {
 
   Future<void> shutdown() async {
     await _debugSessions.toList().map(removeDebugSession).wait;
-    await dtdProcess.kill();
-    await dtdProcess.shouldExit();
     await dtd.close();
+    try {
```
Comment (jakemac53) [inline pkgs/dart_mcp_server/test/test_harness.dart:481]: same for these ones, we will no longer be checking the exit code or that it exited at all.

File: pkgs/dart_mcp_server/test/test_harness.dart [hunk 8]
```diff
@@ -537,16 +579,27 @@ Future<ServerConnectionPair> _initializeMCPServer(
     connection = client.connectServer(clientChannel);
   } else {
     final process = await Process.start(sdk.dartExecutablePath, [
-      'pub', // Using `pub` gives us incremental compilation
```
Comment (jakemac53) [inline pkgs/dart_mcp_server/test/test_harness.dart:540]: Do we need to remove this? The incremental compilation speeds up tests a lot (it is shared across test suites).

File: pkgs/dart_mcp_server/test/test_harness.dart [hunk 9]
```diff
@@ -537,16 +579,27 @@ Future<ServerConnectionPair> _initializeMCPServer(
...
-      'run',
       'bin/main.dart',
       ...cliArgs,
       for (var enabled in featuresConfig.enabledNames) '--enable=$enabled',
       for (var disabled in featuresConfig.disabledNames) '--disable=$disabled',
     ]);
     addTearDown(() async {
-      process.kill();
-      await process.exitCode;
+      try {
```
Comment (jakemac53) [inline pkgs/dart_mcp_server/test/test_harness.dart:587]: A same here, we won't actually wait for exit codes any more.

If `stdin.close()` can fail lets only try/catch that, but not the waiting for the exit code.

File: pkgs/dart_mcp_server/test/test_harness.dart (hunk 4 above)
Comment (Sourav-Sonkar) [reply pkgs/dart_mcp_server/test/test_harness.dart]: This was just from debugging slow CI runs. Reverted back to 5.

File: pkgs/dart_mcp_server/test/test_harness.dart (hunk 5 above)
Comment (Sourav-Sonkar) [reply pkgs/dart_mcp_server/test/test_harness.dart]: Done. Restored dart run and the original flag structure. Also fixed it so --enable-vm-service=0 only goes to Dart apps since Flutter doesn't recognize that flag.

File: pkgs/dart_mcp_server/test/test_harness.dart (hunk 6 above)
Comment (Sourav-Sonkar) [reply pkgs/dart_mcp_server/test/test_harness.dart:338]: You're absolutely right. Changed these to only catch TimeoutException so we still assert the exit codes properly. The graceful shutdown flow is now: try to exit cleanly with timeout, if timeout then kill and wait for actual exit.

File: pkgs/dart_mcp_server/test/test_harness.dart (hunk 8 above)
Comment (Sourav-Sonkar) [reply pkgs/dart_mcp_server/test/test_harness.dart:540]: No we don't need to remove it - you're right about the performance benefit. Restored pub run for the MCP server.

File: pkgs/dart_mcp_server/test/test_harness.dart (hunk 9 above)
Comment (Sourav-Sonkar) [reply pkgs/dart_mcp_server/test/test_harness.dart:587]: Good point. Split the exception handling so stdin.close() failures are caught separately, but we still wait for and assert the exit code.

File: pkgs/dart_mcp_server/test/test_harness.dart (hunk 7 above)
Comment (Sourav-Sonkar) [reply pkgs/dart_mcp_server/test/test_harness.dart:481]: Fixed. Now we only catch exceptions from stdin.close() itself, and the exit code wait is separate so it still asserts proper shutdown.

**Review by jakemac53 — APPROVED** [review]
