### PR TITLE
dart_mcp_server: add `args` parameter to `launch_app` tool

### LINKED ISSUE #342: launch_app: Support --flavor and build configuration flags
## Problem

The `launch_app` MCP tool currently only supports `root`, `device`, `target`, and `timeout` parameters. It builds the command as:

```
flutter run --print-dtd --machine --device-id <device> [--target <target>]
```

Many Flutter projects use **flavors** (build configurations) for environment separation (dev/staging/prod). These projects define Xcode schemes and Android product flavors, making `--flavor` mandatory — without it, the build fails:

```
The Xcode project defines schemes: dev, prod
Error: You must specify a --flavor option to select one of the available schemes.
```

This means `launch_app` cannot be used at all for any project that uses flavors.

## Proposed Solution

Add a `flavor` parameter to `launch_app` that maps to `--flavor <value>`:

```
flutter run --print-dtd --machine --device-id <device> --flavor <flavor> [--target <target>]
```

### Nice to have (future)

Support for additional build flags would also be valuable:
- `--dart-define` / `--dart-define-from-file` (environment variables, API keys)
- `--release` / `--profile` (for profiling sessions)

These could be a single `additionalArgs` list parameter, or individual typed parameters.

## Context

- Flavors are a standard Flutter pattern used by a large portion of production apps
- The [Flutter docs recommend flavors](https://docs.flutter.dev/deployment/flavors) for environment management
- Projects using `--dart-define` for Firebase config also can't use `launch_app` without this support

## Environment

- Dart SDK: 3.11.0-296.4.beta
- Flutter: 3.41.0-0.2.pre
- `dart_mcp_server`: 0.1.2 (bundled with SDK)

### PR DESCRIPTION
**Pull request by soyllamas**
Fixes #342

## Summary

- Adds an `args` list parameter to the `launch_app` tool, allowing callers to forward arbitrary extra flags to `flutter run` (e.g. `--flavor dev`, `--dart-define-from-file env.json`, `--release`).
- Managed flags (`--print-dtd`, `--machine`, `--device-id`, `--target`, `-d`, `-t`) are explicitly blocked with a clear error message — both in exact form and equals-syntax (e.g. `--target=lib/main.dart`).
- Updated CHANGELOG and GEMINI.md.

## Test plan

- [ ] `launch_app forwards additional args to flutter run` — verifies args are appended to the command
- [ ] `launch_app works when args is an empty list` — verifies no regression on omitted/empty args
- [ ] `launch_app forwards flavor args` — verifies `--flavor` works end-to-end
- [ ] `launch_app rejects managed args in args list` — verifies `--device-id` in `args` returns `isError: true`
- [ ] `launch_app rejects managed args with equals syntax` — verifies `--target=lib/alt_main.dart` is also caught

All 14 tests in `flutter_launcher_test.dart` pass. Run with:
```
cd pkgs/dart_mcp_server && dart test test/tools/flutter_launcher_test.dart
```

### CODE REVIEW

File: pkgs/dart_mcp_server/lib/src/mixins/flutter_launcher.dart [hunk 1]
```diff
@@ -76,6 +84,14 @@ base mixin FlutterLauncherSupport
               'available devices to present as choices, use the '
               'list_devices tool.',
         ),
+        'args': Schema.list(
+          items: Schema.string(),
+          description:
+              'Additional arguments to pass to the `flutter run` command. '
+              'For example: ["--flavor", "dev", "--dart-define-from-file", '
+              '"env.json"]. Do not include --print-dtd, --machine, '
```
Comment (jakemac53) [inline pkgs/dart_mcp_server/lib/src/mixins/flutter_launcher.dart]: Lets construct the list of "do not include" flags from the constant above

Comment (soyllamas) [reply pkgs/dart_mcp_server/lib/src/mixins/flutter_launcher.dart]: [678bb42](https://github.com/dart-lang/ai/pull/354/commits/678bb42ddf6bb37f1c2a0f203335e4eb3e24528c) ✅
